### GET index
GET http://localhost:8080/api/v1/


### GET request to retrieve the data
GET http://127.0.0.1:8080/api/v1/uid


### 3. POST distanceTo - valid request
POST http://localhost:8080/api/v1/distanceTo
Content-Type: application/json

{
  "position1": {
    "lng": -3.192473,
    "lat": 55.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.942617
  }
}


### 3. POST distanceTo - invalid request (out of range)
POST http://localhost:8080/api/v1/distanceTo
Content-Type: application/json

{
  "position1": {
    "lng": -200.0,
    "lat": 55.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.942617
  }
}

### 3. POST distanceTo - invalid request (syntactic error - missing field)
POST http://localhost:8080/api/v1/distanceTo
Content-Type: application/json

{
  "position1": {
    "lng": -3.192473
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.942617
  }
}

### 3. POST distanceTo - invalid request (positive longitude - out of Edinburgh area)
POST http://localhost:8080/api/v1/distanceTo
Content-Type: application/json

{
  "position1": {
    "lng": 3.192473,
    "lat": 55.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.942617
  }
}

### 4. POST closeTo - invalid request (negative latitude - out of Edinburgh area)
POST http://localhost:8080/api/v1/closeTo
Content-Type: application/json

{
  "position1": {
    "lng": -3.192473,
    "lat": -55.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.942617
  }
}




### 4. POST closeTo - valid request (close positions)
POST http://localhost:8080/api/v1/closeTo
Content-Type: application/json

{
  "position1": {
    "lng": -3.192473,
    "lat": 55.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.946233
  }
}


### 4. POST closeTo - valid request (far positions)
POST http://localhost:8080/api/v1/closeTo
Content-Type: application/json

{
  "position1": {
    "lng": -3.192473,
    "lat": 55.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.942617
  }
}

### 4. POST closeTo - invalid request (out of range)
POST http://localhost:8080/api/v1/closeTo
Content-Type: application/json

{
  "position1": {
    "lng": -200.0,
    "lat": 50.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.042617
  }
}

### 4. POST closeTo - invalid request (syntactic error - missing field)
POST http://localhost:8080/api/v1/closeTo
Content-Type: application/json

{
  "position1": {
    "lng": -3.992473,
    "lat": 35.946233
  },
  "position2": {
    "lng": -32.192473
  }
}

### 4. POST closeTo - invalid request (negative latitude - out of Edinburgh area)
POST http://localhost:8080/api/v1/closeTo
Content-Type: application/json

{
  "position1": {
    "lng": -3.192473,
    "lat": -55.946233
  },
  "position2": {
    "lng": -3.192473,
    "lat": 55.942617
  }
}



### 5. POST nextPosition - valid request
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
  "start": {
    "lng": -3.192473,
    "lat": 55.946233
  },
  "angle": 45.0
}


### 5. POST nextPosition - hover (angle 999)
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
  "start": {
    "lng": -3.192473,
    "lat": 55.946233
  },
  "angle": 999.0
}

### 5. POST nextPosition - invalid request (out of range)
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
  "start": {
    "lng": -181.0,
    "lat": 55.946233
  },
  "angle": 45.0
}

### 5. POST nextPosition - invalid request (semantic error - angle null)
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
  "start": {
    "lng": -3.192473,
    "lat": 55.946233
  },
  "angle": null
}

### 5. POST nextPosition - invalid request (syntactic error - missing field)
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
  "start": {
    "lng": -3.192473,
    "lat": 55.946233
  }
}

### 5. POST nextPosition - invalid request (angle not multiple of 22.5)
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
  "start": {
    "lng": -3.192473,
    "lat": 55.946233
  },
  "angle": 45.5
}

### 5. POST nextPosition - invalid request (positive longitude - out of Edinburgh area)
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
  "start": {
    "lng": 3.192473,
    "lat": 55.946233
  },
  "angle": 45.0
}




### 6. POST isInRegion - valid request (inside region)
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": -3.188,
    "lat": 55.944
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.946233
      }
    ]
  }
}


### 6. POST isInRegion - valid request (outside region)
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": -3.180,
    "lat": 55.944
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.946233
      }
    ]
  }
}


### 6. POST isInRegion - invalid request (unclosed region)
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": -3.188,
    "lat": 55.944
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.946233
      }
    ]
  }
}

### 6. POST isInRegion - invalid request (syntactic error - missing field)
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": -3.188
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.946233
      }
    ]
  }
}

### 6.POST isInRegion - invalid request (out of range)
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": -3.188,
    "lat": 100.0
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.946233
      }
    ]
  }
}

### 6. POST isInRegion - invalid request (inadequate vertices)
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": -3.188,
    "lat": 55.944
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      }
    ]
  }
}

